substitutions:
  _PROJECT_ID_NEW: ${PROJECT_ID//4/-}
 
steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - gcr.io/$PROJECT_ID/cloud-run-cloud-build
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/cloud-run-cloud-build
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - cloud-run-cloud-build
      - '--image'
      - gcr.io/$PROJECT_ID/cloud-run-cloud-build
      - '--region'
      - europe-west4
      - --allow-unauthenticated
      - '--revision-suffix'
      - '${_PROJECT_ID_NEW}'
images:
  - gcr.io/$PROJECT_ID/cloud-run-cloud-build
options:
     dynamic_substitutions: true  