steps:
  - name: 'ubuntu'
    args: ['bash', './myscript.sh']
    env:
    - 'BUILD=$BUILD_ID'
    - 'PROJECT_ID=$PROJECT_ID'
    - 'PROJECT_NUMBE=echo "${PROJECT_NUMBER//[5]/X}"'
    - 'REV=$REVISION_ID'
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - gcr.io/$PROJECT_ID/cloud-run-cloud-build
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/cloud-run-cloud-build
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - cloud-run-cloud-build
      - '--image'
      - gcr.io/$PROJECT_ID/cloud-run-cloud-build
      - '--region'
      - europe-west4
      - --allow-unauthenticated
      - '--revision-suffix'
      - $PROJECT_NUMBE
images:
  - gcr.io/$PROJECT_ID/cloud-run-cloud-build
