steps:
  # - name: gcr.io/cloud-builders/docker
  #   args:
  #     - build
  #     - '-t'
  #     - gcr.io/landing-zone-demo-341118/cloud-run-cloud-build
  #     - .
  # - name: gcr.io/cloud-builders/docker
  #   args:
  #     - push
  #     - gcr.io/landing-zone-demo-341118/cloud-run-cloud-build
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - cloud-run-cloud-build
      - '--image'
      - gcr.io/landing-zone-demo-341118/cloud-run-cloud-build
      - '--region'
      - us-central1
      - --allow-unauthenticated
images:
  - gcr.io/landing-zone-demo-341118/cloud-run-cloud-build
