steps:
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  args: ['echo','${PROJECT_ID}'] # landing-zone-demo-341118
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  args: ['echo','${PROJECT_ID^^}'] # ${PROJECT_ID^^}

  # - name: gcr.io/google.com/cloudsdktool/cloud-sdk
  #   entrypoint: gcloud
  #   args:
  #     - run
  #     - deploy
  #     - cloud-run-cloud-build
  #     - '--image'
  #     - gcr.io/$PROJECT_ID/cloud-run-cloud-build
  #     - '--region'
  #     - europe-west4
  #     - --allow-unauthenticated
  #     - '--revision-suffix'
  #     # - ${PROJECT_NUMBER//5/k}
  #     - ${PROJECT_NUMBER:5}
  #     # - $PROJECT_NUMBER
  #     # - '${_PROJECT_NUMBE}'
options:
     dynamic_substitutions: true  